import 'package:agrupapiro/constants/database_constants/database_grupo_pesquisa.dart';
import 'package:agrupapiro/constants/database_constants/database_tarefa.dart';

const String kTAREFA_GRUPO_PESQUISA_TABLENAME = 'tarefa_grupo_pesquisa';

const String kTAREFA_GRUPO_PESQUISA_TAREFA_ID = 'tarefa_id';
const String kTAREFA_GRUPO_PESQUISA_GRUPO_PESQUISA_ID = 'grupo_pesquisa_id';

const String kTAREFA_GRUPO_PESQUISA_CREATE_TABLE = '''
  CREATE TABLE $kTAREFA_GRUPO_PESQUISA_TABLENAME (
    $kTAREFA_GRUPO_PESQUISA_TAREFA_ID TEXT NOT NULL,
    $kTAREFA_GRUPO_PESQUISA_GRUPO_PESQUISA_ID TEXT NOT NULL,
    PRIMARY KEY ($kTAREFA_GRUPO_PESQUISA_TAREFA_ID, $kTAREFA_GRUPO_PESQUISA_GRUPO_PESQUISA_ID),
    FOREIGN KEY ($kTAREFA_GRUPO_PESQUISA_TAREFA_ID) REFERENCES $kTAREFA_TABLE_NAME($kTAREFA_COLUMN_ID),
    FOREIGN KEY ($kTAREFA_GRUPO_PESQUISA_GRUPO_PESQUISA_ID) REFERENCES $kGRUPO_PESQUISA_TABLE_NAME($kGRUPO_PESQUISA_ID)
  );
''';
