const String kGRUPO_PESQUISA_TABLE_NAME = 'grupo_pesquisa';
const String kGRUPO_PESQUISA_ID = 'id';
const String kGRUPO_PESQUISA_NOME = 'nome';
const String kGRUPO_PESQUISA_SIGLA = 'sigla';
const String kGRUPO_PESQUISA_DESCRICAO = 'descricao';
const String kGRUPO_PESQUISA_DATA_CRIACAO = 'data_criacao';
const String kGRUPO_PESQUISA_INSTITUICAO = 'instituicao';
const String kGRUPO_PESQUISA_DEPARTAMENTO = 'departamento';

const String kGRUPO_PESQUISA_CREATE_TABLE = '''
  CREATE TABLE $kGRUPO_PESQUISA_TABLE_NAME (
    $kGRUPO_PESQUISA_ID TEXT PRIMARY KEY,
    $kGRUPO_PESQUISA_NOME TEXT NOT NULL,
    $kGRUPO_PESQUISA_SIGLA TEXT NOT NULL,
    $kGRUPO_PESQUISA_DESCRICAO TEXT NOT NULL,
    $kGRUPO_PESQUISA_DATA_CRIACAO INTEGER NOT NULL,
    $kGRUPO_PESQUISA_INSTITUICAO TEXT NOT NULL,
    $kGRUPO_PESQUISA_DEPARTAMENTO TEXT NOT NULL
  );
''';
