const String kTAREFA_TABLE_NAME = 'tarefa';
const String kTAREFA_COLUMN_ID = 'id';
const String kTAREFA_COLUMN_TITULO = 'titulo';
const String kTAREFA_COLUMN_DESCRICAO = 'descricao';
const String kTAREFA_COLUMN_DATA_ENTREGA = 'data_entrega';
const String kTAREFA_COLUMN_DATA_CRIACAO = 'data_criacao';
const String kTAREFA_COLUMN_ID_GRUPO_PESQUISA = 'id_grupo_pesquisa';
const String kTAREFA_COLUMN_ID_USUARIO = 'id_usuario';
const String kTAREFA_COLUMN_STATUS = 'status';

const String kTAREFA_CREATE_TABLE = '''
  CREATE TABLE $kTAREFA_TABLE_NAME (
    $kTAREFA_COLUMN_ID TEXT PRIMARY KEY,
    $kTAREFA_COLUMN_TITULO TEXT NOT NULL,
    $kTAREFA_COLUMN_DESCRICAO TEXT NOT NULL,
    $kTAREFA_COLUMN_DATA_ENTREGA INTEGER NOT NULL,
    $kTAREFA_COLUMN_DATA_CRIACAO INTEGER NOT NULL,
    $kTAREFA_COLUMN_ID_GRUPO_PESQUISA TEXT NOT NULL,
    $kTAREFA_COLUMN_ID_USUARIO TEXT NOT NULL,
    $kTAREFA_COLUMN_STATUS TEXT NOT NULL
  );
''';
